/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package superliga;

import java.awt.Color;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;

/**
 *
 * @author Укиии Цар
 */
public class admin extends javax.swing.JFrame {

    /**
     * Creates new form admin
     */
    
    public void closeCurrent() {
        WindowEvent winClosingEvent = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }
    
    public admin() {
        initComponents();
        setResizable(false);
        setTitle("Administrator");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        b_dodajKlub = new javax.swing.JButton();
        b_izbaciKlub = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        KLUBOVI = new javax.swing.JLabel();
        jToolBar2 = new javax.swing.JToolBar();
        b_zakaziUtakmicu = new javax.swing.JButton();
        b_promeniTermin = new javax.swing.JButton();
        b_otkaziUtakmicu = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        KLUBOVI1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(null);

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        b_dodajKlub.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        b_dodajKlub.setIcon(new javax.swing.ImageIcon(getClass().getResource("/slike/add-circle-green-512.png"))); // NOI18N
        b_dodajKlub.setText("Dodaj klub u ligu");
        b_dodajKlub.setFocusable(false);
        b_dodajKlub.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        b_dodajKlub.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        b_dodajKlub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_dodajKlubActionPerformed(evt);
            }
        });
        jToolBar1.add(b_dodajKlub);

        b_izbaciKlub.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        b_izbaciKlub.setIcon(new javax.swing.ImageIcon(getClass().getResource("/slike/Untitled-25-512.png"))); // NOI18N
        b_izbaciKlub.setText("Izbaci klub iz lige");
        b_izbaciKlub.setFocusable(false);
        b_izbaciKlub.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        b_izbaciKlub.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        b_izbaciKlub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_izbaciKlubActionPerformed(evt);
            }
        });
        jToolBar1.add(b_izbaciKlub);

        jPanel1.add(jToolBar1);
        jToolBar1.setBounds(0, 20, 320, 70);

        KLUBOVI.setBackground(new java.awt.Color(255, 204, 0));
        KLUBOVI.setFont(new java.awt.Font("Calibri", 1, 22)); // NOI18N
        KLUBOVI.setText("KLUBOVI");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(KLUBOVI, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(157, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(KLUBOVI)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 320, 20);

        jToolBar2.setFloatable(false);
        jToolBar2.setRollover(true);

        b_zakaziUtakmicu.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        b_zakaziUtakmicu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/slike/add-circle-green-512.png"))); // NOI18N
        b_zakaziUtakmicu.setText("Zakaži utakmicu");
        b_zakaziUtakmicu.setFocusable(false);
        b_zakaziUtakmicu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        b_zakaziUtakmicu.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        b_zakaziUtakmicu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_zakaziUtakmicuActionPerformed(evt);
            }
        });
        jToolBar2.add(b_zakaziUtakmicu);

        b_promeniTermin.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        b_promeniTermin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/slike/change.png"))); // NOI18N
        b_promeniTermin.setText("Promeni termin");
        b_promeniTermin.setFocusable(false);
        b_promeniTermin.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        b_promeniTermin.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        b_promeniTermin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_promeniTerminActionPerformed(evt);
            }
        });
        jToolBar2.add(b_promeniTermin);

        b_otkaziUtakmicu.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        b_otkaziUtakmicu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/slike/Untitled-25-512.png"))); // NOI18N
        b_otkaziUtakmicu.setText("Otkaži utakmicu");
        b_otkaziUtakmicu.setFocusable(false);
        b_otkaziUtakmicu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        b_otkaziUtakmicu.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        b_otkaziUtakmicu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_otkaziUtakmicuActionPerformed(evt);
            }
        });
        jToolBar2.add(b_otkaziUtakmicu);

        jPanel1.add(jToolBar2);
        jToolBar2.setBounds(320, 20, 300, 70);

        KLUBOVI1.setBackground(new java.awt.Color(255, 204, 0));
        KLUBOVI1.setFont(new java.awt.Font("Calibri", 1, 22)); // NOI18N
        KLUBOVI1.setText("UTAKMICE");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(116, Short.MAX_VALUE)
                .addComponent(KLUBOVI1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(98, 98, 98))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(KLUBOVI1)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3);
        jPanel3.setBounds(300, 0, 320, 20);

        jButton1.setText("Odjavi se");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(270, 350, 80, 23);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/slike/superliga-2018_3.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 620, 375);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b_izbaciKlubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_izbaciKlubActionPerformed
        izbaciKlub ik = new izbaciKlub();
        ik.setVisible(true);
    }//GEN-LAST:event_b_izbaciKlubActionPerformed

    private void b_dodajKlubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_dodajKlubActionPerformed
        dodajKlub dk = new dodajKlub();
        dk.setVisible(true);
    }//GEN-LAST:event_b_dodajKlubActionPerformed

    private void b_zakaziUtakmicuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_zakaziUtakmicuActionPerformed
        zakaziUtakmicu zk = new zakaziUtakmicu();
        zk.setVisible(true);
    }//GEN-LAST:event_b_zakaziUtakmicuActionPerformed

    private void b_promeniTerminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_promeniTerminActionPerformed
        promeniTermin pt = new promeniTermin();
        pt.setVisible(true);
    }//GEN-LAST:event_b_promeniTerminActionPerformed

    private void b_otkaziUtakmicuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_otkaziUtakmicuActionPerformed
        otkaziUtakmicu ou = new otkaziUtakmicu();
        ou.setVisible(true);
    }//GEN-LAST:event_b_otkaziUtakmicuActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        loginForm lf = new loginForm();
        lf.setVisible(true);
        closeCurrent();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel KLUBOVI;
    private javax.swing.JLabel KLUBOVI1;
    private javax.swing.JButton b_dodajKlub;
    private javax.swing.JButton b_izbaciKlub;
    private javax.swing.JButton b_otkaziUtakmicu;
    private javax.swing.JButton b_promeniTermin;
    private javax.swing.JButton b_zakaziUtakmicu;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar2;
    // End of variables declaration//GEN-END:variables
}
