/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package superliga;

import javax.swing.JOptionPane;

/**
 *
 * @author Укиии Цар
 */
public class dodajKlub extends javax.swing.JFrame {

    Baza baza = new Baza();
    
    public dodajKlub() {
        initComponents();
        setResizable(false);
        setTitle("Dodaj klub u Superligu Srbije");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        tf_dodajKlub = new javax.swing.JTextField();
        b_submit_dodajKlub = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel2.setText("Ime kluba:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 180, 80, 23);

        tf_dodajKlub.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        tf_dodajKlub.setPreferredSize(new java.awt.Dimension(100, 29));
        tf_dodajKlub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_dodajKlubActionPerformed(evt);
            }
        });
        jPanel1.add(tf_dodajKlub);
        tf_dodajKlub.setBounds(120, 180, 150, 23);

        b_submit_dodajKlub.setText("Dodaj klub u ligu");
        b_submit_dodajKlub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_submit_dodajKlubActionPerformed(evt);
            }
        });
        jPanel1.add(b_submit_dodajKlub);
        b_submit_dodajKlub.setBounds(280, 180, 120, 23);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/slike/Superliga-srbije-logo.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 440, 220);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf_dodajKlubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_dodajKlubActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_dodajKlubActionPerformed

    private void b_submit_dodajKlubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_submit_dodajKlubActionPerformed
        try {
            baza.poveziSaBazom();
            
            String queryDodajKlub = "INSERT INTO klubovi(ime_kluba) VALUES('" + tf_dodajKlub.getText() + "')";
            baza.naredba.executeUpdate(queryDodajKlub);
            
            JOptionPane.showMessageDialog(null, "Uspešno ste dodali fudbalski klub " + tf_dodajKlub.getText() + " u Superligu Srbije!", "OBAVEŠTENJE", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            System.out.println("Greska sa bazom: " + e);
        } finally {
            baza.zatvoriBazu();
        }
        tf_dodajKlub.setText(null);
    }//GEN-LAST:event_b_submit_dodajKlubActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dodajKlub.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dodajKlub.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dodajKlub.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dodajKlub.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dodajKlub().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_submit_dodajKlub;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField tf_dodajKlub;
    // End of variables declaration//GEN-END:variables
}
