/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package superliga;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Укиии Цар
 */
public class izbaciKlub extends javax.swing.JFrame {

    Baza baza = new Baza();
    
    private void ucitajKlubove() {
        try {
            baza.poveziSaBazom();

            String queryIzaberiKlub = "SELECT ime_kluba FROM klubovi";
            ResultSet rezultatIzaberiKlub = baza.naredba.executeQuery(queryIzaberiKlub);
            while(rezultatIzaberiKlub.next()) {
                cb_izaberiKlub.addItem(rezultatIzaberiKlub.getString("ime_kluba"));
            }
        } catch (Exception e) {
            System.out.println("Greska - combobox: " + e);
        } finally {
            baza.zatvoriBazu();
        }
    }
    
    public void refreshCurrent() {
        WindowEvent winClosingEvent = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
        
        izbaciKlub ik = new izbaciKlub();
        ik.setVisible(true);
    }
    
    public izbaciKlub() {
        initComponents();
        setResizable(false);
        setTitle("Izbaci klub iz Superlige Srbije");
        ucitajKlubove();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        b_submit_izbaciKlub = new javax.swing.JButton();
        cb_izaberiKlub = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(null);

        b_submit_izbaciKlub.setText("Izbaci klub iz lige");
        b_submit_izbaciKlub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_submit_izbaciKlubActionPerformed(evt);
            }
        });
        jPanel1.add(b_submit_izbaciKlub);
        b_submit_izbaciKlub.setBounds(290, 180, 120, 23);

        cb_izaberiKlub.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jPanel1.add(cb_izaberiKlub);
        cb_izaberiKlub.setBounds(130, 180, 150, 23);

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel1.setText("Izaberi klub:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(30, 180, 100, 23);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/slike/Superliga-srbije-logo.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 440, 220);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 440, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b_submit_izbaciKlubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_submit_izbaciKlubActionPerformed
        try {
            baza.poveziSaBazom();
            
            String queryIzbaciKlub = "DELETE FROM klubovi WHERE ime_kluba='" + cb_izaberiKlub.getSelectedItem() + "'";
            baza.naredba.executeUpdate(queryIzbaciKlub);
            
            JOptionPane.showMessageDialog(null, "Uspešno ste izbacili fudbalski klub " + cb_izaberiKlub.getSelectedItem() + " iz Superlige Srbije!", "OBAVEŠTENJE", JOptionPane.INFORMATION_MESSAGE);
            refreshCurrent();
        } catch (Exception e) {
            System.out.println("Greska - izbaci klub: " + e);
        } finally {
            baza.zatvoriBazu();
        }
    }//GEN-LAST:event_b_submit_izbaciKlubActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(izbaciKlub.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(izbaciKlub.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(izbaciKlub.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(izbaciKlub.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new izbaciKlub().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_submit_izbaciKlub;
    private javax.swing.JComboBox<String> cb_izaberiKlub;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
