/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package superliga;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Укиии Цар
 */
public class otkaziUtakmicu extends javax.swing.JFrame {

    Baza baza = new Baza();
    
    ArrayList<String> domacini=new ArrayList<String>();
    ArrayList<String> gosti=new ArrayList<String>();
    ArrayList<String> datumi=new ArrayList<String>();
    ArrayList<Integer> domaciniID=new ArrayList<Integer>();
    ArrayList<Integer> gostiID=new ArrayList<Integer>();
    
    String datum;
    int domacinInt = 0;
    int gostInt = 0;
    
    public void closeCurrent() {
        WindowEvent winClosingEvent = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }
    
    public otkaziUtakmicu() {
        initComponents();
        setResizable(false);
        setTitle("Otkaži utakmicu");
        
        try {
            baza.poveziSaBazom();

            String queryDomacini = "SELECT klubovi.ime_kluba FROM klubovi JOIN utakmice ON domacin_id = id_kluba";
            ResultSet rezultatDomacini = baza.naredba.executeQuery(queryDomacini);
            while(rezultatDomacini.next()) {
                domacini.add(rezultatDomacini.getString("ime_kluba"));
            }
            
            String queryGosti = "SELECT klubovi.ime_kluba FROM klubovi JOIN utakmice ON gost_id = id_kluba";
            ResultSet rezultatGosti = baza.naredba.executeQuery(queryGosti);
            while(rezultatGosti.next()) {
                gosti.add(rezultatGosti.getString("ime_kluba"));
            }
            
            for(int i = 0; i < domacini.size(); i++) {
                String queryDomacinID = "SELECT id_kluba FROM klubovi WHERE ime_kluba='" + domacini.get(i) + "'";
                ResultSet rezultatDomacinID = baza.naredba.executeQuery(queryDomacinID);
                while(rezultatDomacinID.next()) {
                    domaciniID.add(Integer.parseInt(rezultatDomacinID.getString("id_kluba")));
                }
            }
            
            for(int i = 0; i < domacini.size(); i++) {
                String queryGostID = "SELECT id_kluba FROM klubovi WHERE ime_kluba='" + gosti.get(i) + "'";
                ResultSet rezultatGostID = baza.naredba.executeQuery(queryGostID);
                while(rezultatGostID.next()) {
                    gostiID.add(Integer.parseInt(rezultatGostID.getString("id_kluba")));
                }
            }
            
            for(int i = 0; i < domacini.size(); i++) {
                String queryDatum = "SELECT datum FROM utakmice WHERE domacin_ID='" + domaciniID.get(i) + "' AND gost_ID='" + gostiID.get(i) + "'";
                ResultSet rezultatDatum = baza.naredba.executeQuery(queryDatum);
                while(rezultatDatum.next()) {
                    datum = rezultatDatum.getString("datum");
                    String[] datumParts = datum.split(" ");
                    String part1 = datumParts[0];
                    datumi.add(part1);
                } 
            }
            
            for(int i = 0; i < domacini.size(); i++) {
                cb_izaberiUtakmicu.addItem(domacini.get(i) + " - " + gosti.get(i) + " - " + datumi.get(i));
            }
        } catch (Exception e) {
            System.out.println("Greska - combobox: " + e);
        } finally {
            baza.zatvoriBazu();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        b_otkaziUtakmicu = new javax.swing.JButton();
        cb_izaberiUtakmicu = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(null);

        b_otkaziUtakmicu.setText("Otkaži utakmicu");
        b_otkaziUtakmicu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_otkaziUtakmicuActionPerformed(evt);
            }
        });
        jPanel1.add(b_otkaziUtakmicu);
        b_otkaziUtakmicu.setBounds(40, 160, 110, 23);

        cb_izaberiUtakmicu.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        cb_izaberiUtakmicu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_izaberiUtakmicuActionPerformed(evt);
            }
        });
        jPanel1.add(cb_izaberiUtakmicu);
        cb_izaberiUtakmicu.setBounds(40, 120, 250, 23);

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel2.setText("IZABERI UTAKMICU");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(40, 90, 150, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/slike/super-liga-srbije-26.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 620, 298);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b_otkaziUtakmicuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_otkaziUtakmicuActionPerformed
        try {
            baza.poveziSaBazom();
            
            int index = cb_izaberiUtakmicu.getSelectedIndex();
        
            String domacin = domacini.get(index);
            String gost = gosti.get(index);
            
            String queryDomacinID = "SELECT id_kluba FROM klubovi WHERE ime_kluba='" + domacin + "'";
            ResultSet rezultatDomacinID = baza.naredba.executeQuery(queryDomacinID);
            while(rezultatDomacinID.next()) {
                domacinInt = Integer.parseInt(rezultatDomacinID.getString("id_kluba"));
            }
            
            String queryGostID = "SELECT id_kluba FROM klubovi WHERE ime_kluba='" + gost + "'";
            ResultSet rezultatGostID = baza.naredba.executeQuery(queryGostID);
            while(rezultatGostID.next()) {
                gostInt = Integer.parseInt(rezultatGostID.getString("id_kluba"));
            }
            
            String izbrisi = "DELETE FROM utakmice WHERE domacin_id='" + domacinInt + "' AND gost_id='" + gostInt + "'";
            baza.naredba.executeUpdate(izbrisi);
            
            JOptionPane.showMessageDialog(null, "Uspešno ste otkazali utakmicu između izabranih timova!", "OBAVEŠTENJE!", JOptionPane.INFORMATION_MESSAGE);
            
            closeCurrent();
            otkaziUtakmicu ou = new otkaziUtakmicu();
            ou.setVisible(true);
        } catch (Exception e) {
            System.out.println("Greska - brisanje: " + e);
        } finally {
            baza.zatvoriBazu();
        }
    }//GEN-LAST:event_b_otkaziUtakmicuActionPerformed

    private void cb_izaberiUtakmicuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_izaberiUtakmicuActionPerformed
   
    }//GEN-LAST:event_cb_izaberiUtakmicuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(otkaziUtakmicu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(otkaziUtakmicu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(otkaziUtakmicu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(otkaziUtakmicu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new otkaziUtakmicu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_otkaziUtakmicu;
    private javax.swing.JComboBox<String> cb_izaberiUtakmicu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
